// Code generated by MockGen. DO NOT EDIT.
// Source: /home/nakamuraitsuki/program/webRTC-practice2/backend/internal/usecase/websocketcase/interface.go
//
// Generated by this command:
//
//	mockgen -source=/home/nakamuraitsuki/program/webRTC-practice2/backend/internal/usecase/websocketcase/interface.go -destination=test/mocks/usecase/websocketcase/interface_mock.go
//

// Package mock_websocketcase is a generated GoMock package.
package mock_websocketcase

import (
	context "context"
	reflect "reflect"

	entity "example.com/infrahandson/internal/domain/entity"
	websocketcase "example.com/infrahandson/internal/usecase/websocketcase"
	gomock "go.uber.org/mock/gomock"
)

// MockWebsocketUseCaseInterface is a mock of WebsocketUseCaseInterface interface.
type MockWebsocketUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWebsocketUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockWebsocketUseCaseInterfaceMockRecorder is the mock recorder for MockWebsocketUseCaseInterface.
type MockWebsocketUseCaseInterfaceMockRecorder struct {
	mock *MockWebsocketUseCaseInterface
}

// NewMockWebsocketUseCaseInterface creates a new mock instance.
func NewMockWebsocketUseCaseInterface(ctrl *gomock.Controller) *MockWebsocketUseCaseInterface {
	mock := &MockWebsocketUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockWebsocketUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebsocketUseCaseInterface) EXPECT() *MockWebsocketUseCaseInterfaceMockRecorder {
	return m.recorder
}

// ConnectUserToRoom mocks base method.
func (m *MockWebsocketUseCaseInterface) ConnectUserToRoom(ctx context.Context, req websocketcase.ConnectUserToRoomRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectUserToRoom", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectUserToRoom indicates an expected call of ConnectUserToRoom.
func (mr *MockWebsocketUseCaseInterfaceMockRecorder) ConnectUserToRoom(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectUserToRoom", reflect.TypeOf((*MockWebsocketUseCaseInterface)(nil).ConnectUserToRoom), ctx, req)
}

// DisconnectUser mocks base method.
func (m *MockWebsocketUseCaseInterface) DisconnectUser(ctx context.Context, req websocketcase.DisconnectUserRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisconnectUser", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisconnectUser indicates an expected call of DisconnectUser.
func (mr *MockWebsocketUseCaseInterfaceMockRecorder) DisconnectUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisconnectUser", reflect.TypeOf((*MockWebsocketUseCaseInterface)(nil).DisconnectUser), ctx, req)
}

// SendICECandidate mocks base method.
func (m *MockWebsocketUseCaseInterface) SendICECandidate(ctx context.Context, iceCandidate *entity.ICECandidate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendICECandidate", ctx, iceCandidate)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendICECandidate indicates an expected call of SendICECandidate.
func (mr *MockWebsocketUseCaseInterfaceMockRecorder) SendICECandidate(ctx, iceCandidate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendICECandidate", reflect.TypeOf((*MockWebsocketUseCaseInterface)(nil).SendICECandidate), ctx, iceCandidate)
}

// SendSDPMessage mocks base method.
func (m *MockWebsocketUseCaseInterface) SendSDPMessage(ctx context.Context, sdpMsg *entity.SDPMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSDPMessage", ctx, sdpMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendSDPMessage indicates an expected call of SendSDPMessage.
func (mr *MockWebsocketUseCaseInterfaceMockRecorder) SendSDPMessage(ctx, sdpMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSDPMessage", reflect.TypeOf((*MockWebsocketUseCaseInterface)(nil).SendSDPMessage), ctx, sdpMsg)
}

// SendTextMessage mocks base method.
func (m *MockWebsocketUseCaseInterface) SendTextMessage(ctx context.Context, req websocketcase.SendTextRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTextMessage", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTextMessage indicates an expected call of SendTextMessage.
func (mr *MockWebsocketUseCaseInterfaceMockRecorder) SendTextMessage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTextMessage", reflect.TypeOf((*MockWebsocketUseCaseInterface)(nil).SendTextMessage), ctx, req)
}
